// source: http://www.82games.com/1314/ROLRTG8.HTM
var players = [
    {
        Team: "MIN",
        Player: "Love",
        Min: "74%",
        Own: 30.9,
        Opp: 17.7,
        Net: 13.3,
        On: 18.7,
        Off: -21.3,
        Net: 40,
        Rating: 18.8,
    },
    {
        Team: "GSW",
        Player: "Lee",
        Min: "62%",
        Own: 21.2,
        Opp: 12.7,
        Net: 8.4,
        On: 20.5,
        Off: -13.1,
        Net: 33.6,
        Rating: 15.6,
    },
    {
        Team: "GSW",
        Player: "Iguodala",
        Min: "77%",
        Own: 21.1,
        Opp: 12.8,
        Net: 8.3,
        On: 15.5,
        Off: -18.1,
        Net: 33.6,
        Rating: 15.6,
    },
    {
        Team: "IND",
        Player: "Hibbert",
        Min: "62%",
        Own: 19.8,
        Opp: 5.8,
        Net: 14,
        On: 15.6,
        Off: -0.5,
        Net: 16.1,
        Rating: 14.7,
    },
    {
        Team: "NOH",
        Player: "Davis",
        Min: "74%",
        Own: 31.7,
        Opp: 12.8,
        Net: 18.9,
        On: 3.5,
        Off: -2.7,
        Net: 6.2,
        Rating: 14.7,
    },
    {
        Team: "IND",
        Player: "George",
        Min: "74%",
        Own: 22.5,
        Opp: 8,
        Net: 14.5,
        On: 13,
        Off: -0.8,
        Net: 13.7,
        Rating: 14.3,
    },
    {
        Team: "LAC",
        Player: "Paul",
        Min: "75%",
        Own: 28.7,
        Opp: 16.1,
        Net: 12.6,
        On: 8.5,
        Off: -8.6,
        Net: 17,
        Rating: 14.1,
    },
    {
        Team: "LAC",
        Player: "Griffin",
        Min: "79%",
        Own: 24.2,
        Opp: 16.8,
        Net: 7.3,
        On: 10.2,
        Off: -17.2,
        Net: 27.4,
        Rating: 14,
    },
    {
        Team: "GSW",
        Player: "Thompson",
        Min: "73%",
        Own: 22.8,
        Opp: 13.2,
        Net: 9.6,
        On: 13.6,
        Off: -8.1,
        Net: 21.7,
        Rating: 13.6,
    },
    {
        Team: "LAC",
        Player: "Redick",
        Min: "62%",
        Own: 20.8,
        Opp: 15.1,
        Net: 5.7,
        On: 15.4,
        Off: -13.6,
        Net: 29,
        Rating: 13.5,
    },
    {
        Team: "GSW",
        Player: "Curry",
        Min: "61%",
        Own: 24.6,
        Opp: 16.1,
        Net: 8.6,
        On: 16.4,
        Off: -5.9,
        Net: 22.3,
        Rating: 13.1,
    },
    {
        Team: "HOU",
        Player: "Harden",
        Min: "73%",
        Own: 22.2,
        Opp: 6.7,
        Net: 15.5,
        On: 4.7,
        Off: -3.6,
        Net: 8.3,
        Rating: 13.1,
    },
    {
        Team: "NYK",
        Player: "Anthony",
        Min: "83%",
        Own: 22.4,
        Opp: 15.4,
        Net: 7,
        On: -1.3,
        Off: -25.4,
        Net: 24,
        Rating: 12.7,
    },
    {
        Team: "SAS",
        Player: "Diaw",
        Min: "50%",
        Own: 19.2,
        Opp: 9.5,
        Net: 9.7,
        On: 17.7,
        Off: 0.8,
        Net: 16.9,
        Rating: 12.1,
    },
    {
        Team: "CHI",
        Player: "Deng",
        Min: "75%",
        Own: 18,
        Opp: 12,
        Net: 6,
        On: 10.9,
        Off: -12.4,
        Net: 23.2,
        Rating: 11.7,
    },
    {
        Team: "CHI",
        Player: "Butler",
        Min: "64%",
        Own: 17.4,
        Opp: 4.4,
        Net: 13.1,
        On: 7.6,
        Off: 0.3,
        Net: 7.3,
        Rating: 11.1,
    },
    {
        Team: "BKN",
        Player: "Lopez",
        Min: "55%",
        Own: 28.7,
        Opp: 13.1,
        Net: 15.6,
        On: -3.7,
        Off: -5.8,
        Net: 2,
        Rating: 11.1,
    },
    {
        Team: "SAC",
        Player: "Thomas",
        Min: "59%",
        Own: 24.3,
        Opp: 13.9,
        Net: 10.4,
        On: 0,
        Off: -11.9,
        Net: 11.9,
        Rating: 10.9,
    },
    {
        Team: "POR",
        Player: "Matthews",
        Min: "71%",
        Own: 19.2,
        Opp: 8.7,
        Net: 10.5,
        On: 8.2,
        Off: -3.4,
        Net: 11.6,
        Rating: 10.9,
    },
    {
        Team: "MIA",
        Player: "James",
        Min: "75%",
        Own: 32.2,
        Opp: 12.2,
        Net: 20,
        On: 5.5,
        Off: 13.6,
        Net: -8.1,
        Rating: 10.6,
    },
    {
        Team: "MIN",
        Player: "Martin",
        Min: "66%",
        Own: 22.1,
        Opp: 9.8,
        Net: 12.4,
        On: 10.3,
        Off: 4.2,
        Net: 6,
        Rating: 10.3,
    },
    {
        Team: "WAS",
        Player: "Beal",
        Min: "81%",
        Own: 12.7,
        Opp: 12.5,
        Net: 0.2,
        On: 2,
        Off: -31.2,
        Net: 33.2,
        Rating: 10.1,
    },
    {
        Team: "SAS",
        Player: "Green",
        Min: "52%",
        Own: 15,
        Opp: 7.7,
        Net: 7.3,
        On: 16,
        Off: 2.1,
        Net: 13.9,
        Rating: 9.5,
    },
    {
        Team: "POR",
        Player: "Aldridge",
        Min: "77%",
        Own: 20.4,
        Opp: 11.4,
        Net: 9,
        On: 7.2,
        Off: -3,
        Net: 10.2,
        Rating: 9.4,
    },
    {
        Team: "LAL",
        Player: "Hill",
        Min: "44%",
        Own: 27.2,
        Opp: 18,
        Net: 9.2,
        On: 1,
        Off: -8.6,
        Net: 9.5,
        Rating: 9.3,
    },
    {
        Team: "HOU",
        Player: "Casspi",
        Min: "40%",
        Own: 14.6,
        Opp: 13.4,
        Net: 1.3,
        On: 16.1,
        Off: -6.6,
        Net: 22.8,
        Rating: 8.4,
    },
    {
        Team: "ATL",
        Player: "Horford",
        Min: "69%",
        Own: 24.7,
        Opp: 15.2,
        Net: 9.6,
        On: 6.2,
        Off: 0.3,
        Net: 5.9,
        Rating: 8.3,
    },
    {
        Team: "SAS",
        Player: "Parker",
        Min: "66%",
        Own: 21,
        Opp: 11.1,
        Net: 9.9,
        On: 10.7,
        Off: 6.7,
        Net: 3.9,
        Rating: 7.9,
    },
    {
        Team: "MIN",
        Player: "Brewer",
        Min: "68%",
        Own: 12.9,
        Opp: 13.4,
        Net: -0.5,
        On: 16.1,
        Off: -8.3,
        Net: 24.5,
        Rating: 7.8,
    },
    {
        Team: "CHI",
        Player: "Boozer",
        Min: "63%",
        Own: 23.4,
        Opp: 15.8,
        Net: 7.6,
        On: 8,
        Off: 0,
        Net: 8,
        Rating: 7.7,
    },
    {
        Team: "WAS",
        Player: "Wall",
        Min: "74%",
        Own: 16.8,
        Opp: 14.1,
        Net: 2.7,
        On: 0.1,
        Off: -17.5,
        Net: 17.7,
        Rating: 7.7,
    },
    {
        Team: "BOS",
        Player: "Crawford",
        Min: "55%",
        Own: 19.4,
        Opp: 10.3,
        Net: 9.1,
        On: -1.5,
        Off: -6.1,
        Net: 4.6,
        Rating: 7.6,
    },
    {
        Team: "MIA",
        Player: "Cole",
        Min: "50%",
        Own: 13.4,
        Opp: 10.2,
        Net: 3.2,
        On: 15.7,
        Off: -0.6,
        Net: 16.3,
        Rating: 7.6,
    },
    {
        Team: "POR",
        Player: "Batum",
        Min: "73%",
        Own: 17.6,
        Opp: 11.1,
        Net: 6.5,
        On: 7.5,
        Off: -2.2,
        Net: 9.7,
        Rating: 7.6,
    },
    {
        Team: "MEM",
        Player: "Randolph",
        Min: "61%",
        Own: 18.7,
        Opp: 15.7,
        Net: 3,
        On: 4,
        Off: -12.6,
        Net: 16.6,
        Rating: 7.5,
    },
    {
        Team: "MIL",
        Player: "Henson",
        Min: "53%",
        Own: 20.9,
        Opp: 11.6,
        Net: 9.3,
        On: -7.5,
        Off: -9.5,
        Net: 2,
        Rating: 6.9,
    },
    {
        Team: "CLE",
        Player: "Thompson",
        Min: "73%",
        Own: 15.2,
        Opp: 12.4,
        Net: 2.7,
        On: -2.8,
        Off: -17.6,
        Net: 14.9,
        Rating: 6.8,
    },
    {
        Team: "MIN",
        Player: "Rubio",
        Min: "70%",
        Own: 15.2,
        Opp: 17.5,
        Net: -2.3,
        On: 15.7,
        Off: -8.9,
        Net: 24.5,
        Rating: 6.6,
    },
    {
        Team: "PHO",
        Player: "Dragic",
        Min: "43%",
        Own: 16.1,
        Opp: 9.6,
        Net: 6.5,
        On: 7,
        Off: 0,
        Net: 7,
        Rating: 6.6,
    },
    {
        Team: "ATL",
        Player: "Teague",
        Min: "71%",
        Own: 21.7,
        Opp: 16.6,
        Net: 5.1,
        On: 7.1,
        Off: -2.5,
        Net: 9.6,
        Rating: 6.6,
    },
    {
        Team: "OKC",
        Player: "Jackson",
        Min: "48%",
        Own: 14.5,
        Opp: 13.5,
        Net: 1,
        On: 11.2,
        Off: -6.3,
        Net: 17.6,
        Rating: 6.5,
    },
    {
        Team: "SAS",
        Player: "Ginobili",
        Min: "51%",
        Own: 15.3,
        Opp: 9.9,
        Net: 5.4,
        On: 13.5,
        Off: 5.1,
        Net: 8.4,
        Rating: 6.4,
    },
    {
        Team: "IND",
        Player: "West",
        Min: "61%",
        Own: 15.6,
        Opp: 8.6,
        Net: 7,
        On: 11.3,
        Off: 6.4,
        Net: 4.9,
        Rating: 6.3,
    },
    {
        Team: "ATL",
        Player: "Millsap",
        Min: "66%",
        Own: 23.3,
        Opp: 15.9,
        Net: 7.4,
        On: 5.8,
        Off: 1.7,
        Net: 4.1,
        Rating: 6.3,
    },
    {
        Team: "PHO",
        Player: "Markieff.Morris",
        Min: "50%",
        Own: 25.7,
        Opp: 17.5,
        Net: 8.2,
        On: 4.1,
        Off: 1.8,
        Net: 2.4,
        Rating: 6.2,
    },
    {
        Team: "DAL",
        Player: "Nowitzki",
        Min: "67%",
        Own: 21.5,
        Opp: 20.1,
        Net: 1.4,
        On: 8.2,
        Off: -7.6,
        Net: 15.8,
        Rating: 6.2,
    },
    {
        Team: "ORL",
        Player: "Afflalo",
        Min: "76%",
        Own: 20,
        Opp: 13.4,
        Net: 6.6,
        On: 1.4,
        Off: -3.7,
        Net: 5.2,
        Rating: 6.1,
    },
    {
        Team: "DEN",
        Player: "Lawson",
        Min: "76%",
        Own: 23.9,
        Opp: 16.6,
        Net: 7.2,
        On: -0.3,
        Off: -3.8,
        Net: 3.5,
        Rating: 6,
    },
    {
        Team: "CLE",
        Player: "Irving",
        Min: "73%",
        Own: 17.1,
        Opp: 17.2,
        Net: -0.1,
        On: -2.1,
        Off: -19.3,
        Net: 17.2,
        Rating: 5.7,
    },
    {
        Team: "UTA",
        Player: "Burks",
        Min: "59%",
        Own: 11.6,
        Opp: 9.9,
        Net: 1.6,
        On: -6,
        Off: -19.5,
        Net: 13.5,
        Rating: 5.6,
    },
    {
        Team: "MEM",
        Player: "Gasol",
        Min: "74%",
        Own: 20.7,
        Opp: 11.9,
        Net: 8.9,
        On: -2.8,
        Off: -1.1,
        Net: -1.7,
        Rating: 5.4,
    },
    {
        Team: "ORL",
        Player: "Vucevic",
        Min: "72%",
        Own: 20.5,
        Opp: 14.6,
        Net: 6,
        On: 1.1,
        Off: -2.1,
        Net: 3.2,
        Rating: 5.1,
    },
    {
        Team: "MIL",
        Player: "Wolters",
        Min: "67%",
        Own: 13,
        Opp: 17.9,
        Net: -4.9,
        On: -0.3,
        Off: -25,
        Net: 24.7,
        Rating: 5,
    },
    {
        Team: "BOS",
        Player: "Green",
        Min: "68%",
        Own: 15.5,
        Opp: 9.9,
        Net: 5.6,
        On: -2.4,
        Off: -6,
        Net: 3.6,
        Rating: 5,
    },
    {
        Team: "CHI",
        Player: "Dunleavy",
        Min: "45%",
        Own: 13.3,
        Opp: 6.6,
        Net: 6.7,
        On: 5.6,
        Off: 4.5,
        Net: 1,
        Rating: 4.8,
    },
    {
        Team: "MIL",
        Player: "Middleton",
        Min: "54%",
        Own: 11.4,
        Opp: 18.3,
        Net: -6.9,
        On: 4.3,
        Off: -23.7,
        Net: 28,
        Rating: 4.8,
    },
    {
        Team: "CHA",
        Player: "Sessions",
        Min: "43%",
        Own: 21.7,
        Opp: 15.8,
        Net: 5.9,
        On: -3.5,
        Off: -5.1,
        Net: 1.5,
        Rating: 4.4,
    },
    {
        Team: "MIA",
        Player: "Allen",
        Min: "40%",
        Own: 18.9,
        Opp: 17.1,
        Net: 1.8,
        On: 12.9,
        Off: 3.9,
        Net: 9,
        Rating: 4.2,
    },
    {
        Team: "WAS",
        Player: "Nene",
        Min: "48%",
        Own: 18,
        Opp: 13.5,
        Net: 4.5,
        On: -2.7,
        Off: -6,
        Net: 3.3,
        Rating: 4.1,
    },
    {
        Team: "PHI",
        Player: "Carter-Williams",
        Min: "54%",
        Own: 19.1,
        Opp: 17.5,
        Net: 1.6,
        On: -2.3,
        Off: -11.1,
        Net: 8.8,
        Rating: 4,
    },
    {
        Team: "MEM",
        Player: "Allen",
        Min: "54%",
        Own: 18.8,
        Opp: 17,
        Net: 1.8,
        On: 1.3,
        Off: -6.7,
        Net: 8,
        Rating: 3.9,
    },
    {
        Team: "DET",
        Player: "Monroe",
        Min: "75%",
        Own: 19.5,
        Opp: 15.6,
        Net: 3.9,
        On: -2.5,
        Off: -6.2,
        Net: 3.7,
        Rating: 3.8,
    },
    {
        Team: "TOR",
        Player: "DeRozan",
        Min: "77%",
        Own: 15.8,
        Opp: 13.5,
        Net: 2.3,
        On: 1.4,
        Off: -5.5,
        Net: 6.8,
        Rating: 3.8,
    },
    {
        Team: "DAL",
        Player: "Blair",
        Min: "45%",
        Own: 25.8,
        Opp: 21.9,
        Net: 3.9,
        On: 4.6,
        Off: 1.6,
        Net: 3,
        Rating: 3.6,
    },
    {
        Team: "SAS",
        Player: "Splitter",
        Min: "47%",
        Own: 19.5,
        Opp: 17.5,
        Net: 2.1,
        On: 12.7,
        Off: 6.3,
        Net: 6.4,
        Rating: 3.5,
    },
    {
        Team: "TOR",
        Player: "Lowry",
        Min: "72%",
        Own: 16.2,
        Opp: 11.9,
        Net: 4.3,
        On: 0.2,
        Off: -1.2,
        Net: 1.5,
        Rating: 3.4,
    },
    {
        Team: "OKC",
        Player: "Durant",
        Min: "81%",
        Own: 27.5,
        Opp: 13.8,
        Net: 13.7,
        On: -1.2,
        Off: 16.3,
        Net: -17.5,
        Rating: 3.3,
    },
    {
        Team: "GSW",
        Player: "Bogut",
        Min: "52%",
        Own: 14.6,
        Opp: 15.7,
        Net: -1.1,
        On: 13.4,
        Off: 1.5,
        Net: 11.9,
        Rating: 3.2,
    },
    {
        Team: "DEN",
        Player: "A.Miller",
        Min: "43%",
        Own: 16.9,
        Opp: 9.5,
        Net: 7.4,
        On: -4.1,
        Off: 1.2,
        Net: -5.3,
        Rating: 3.2,
    },
    {
        Team: "ATL",
        Player: "Korver",
        Min: "73%",
        Own: 16.4,
        Opp: 14,
        Net: 2.4,
        On: 5.6,
        Off: 1.1,
        Net: 4.5,
        Rating: 3.1,
    },
    {
        Team: "PHI",
        Player: "Hawes",
        Min: "66%",
        Own: 20.8,
        Opp: 17,
        Net: 3.8,
        On: -5.8,
        Off: -7.5,
        Net: 1.7,
        Rating: 3.1,
    },
    {
        Team: "POR",
        Player: "Lillard",
        Min: "77%",
        Own: 19,
        Opp: 16.7,
        Net: 2.2,
        On: 5.8,
        Off: 1.7,
        Net: 4.1,
        Rating: 2.9,
    },
    {
        Team: "TOR",
        Player: "Johnson",
        Min: "61%",
        Own: 16,
        Opp: 17.3,
        Net: -1.3,
        On: 4.1,
        Off: -6.8,
        Net: 10.8,
        Rating: 2.7,
    },
    {
        Team: "HOU",
        Player: "Lin",
        Min: "68%",
        Own: 20,
        Opp: 16,
        Net: 4,
        On: 2.5,
        Off: 2.5,
        Net: -0.1,
        Rating: 2.7,
    },
    {
        Team: "CLE",
        Player: "Waiters",
        Min: "47%",
        Own: 13.1,
        Opp: 12.9,
        Net: 0.2,
        On: -2.8,
        Off: -10.4,
        Net: 7.5,
        Rating: 2.6,
    },
    {
        Team: "BKN",
        Player: "Pierce",
        Min: "55%",
        Own: 16.4,
        Opp: 15.4,
        Net: 1,
        On: -2.2,
        Off: -7.6,
        Net: 5.5,
        Rating: 2.5,
    },
    {
        Team: "BKN",
        Player: "Williams",
        Min: "46%",
        Own: 13.6,
        Opp: 10.9,
        Net: 2.7,
        On: -3.5,
        Off: -5.6,
        Net: 2.1,
        Rating: 2.5,
    },
    {
        Team: "MEM",
        Player: "Conley",
        Min: "68%",
        Own: 23.8,
        Opp: 19.7,
        Net: 4.1,
        On: -2.6,
        Off: -1.9,
        Net: -0.8,
        Rating: 2.5,
    },
    {
        Team: "DAL",
        Player: "Ellis",
        Min: "78%",
        Own: 17.3,
        Opp: 15.6,
        Net: 1.7,
        On: 3.9,
        Off: 0,
        Net: 3.9,
        Rating: 2.4,
    },
    {
        Team: "LAC",
        Player: "Jordan",
        Min: "75%",
        Own: 20.3,
        Opp: 23,
        Net: -2.7,
        On: 7.2,
        Off: -4.5,
        Net: 11.6,
        Rating: 2.1,
    },
    {
        Team: "NOH",
        Player: "Gordon",
        Min: "64%",
        Own: 21.1,
        Opp: 18.6,
        Net: 2.5,
        On: 2.4,
        Off: 1.1,
        Net: 1.3,
        Rating: 2.1,
    },
    {
        Team: "ORL",
        Player: "Nicholson",
        Min: "41%",
        Own: 14,
        Opp: 14.7,
        Net: -0.7,
        On: 4.6,
        Off: -2.8,
        Net: 7.5,
        Rating: 2,
    },
    {
        Team: "LAL",
        Player: "Meeks",
        Min: "57%",
        Own: 16.9,
        Opp: 18.7,
        Net: -1.8,
        On: -0.3,
        Off: -10,
        Net: 9.7,
        Rating: 2,
    },
    {
        Team: "MIL",
        Player: "Pachulia",
        Min: "55%",
        Own: 14.9,
        Opp: 17.9,
        Net: -3,
        On: -3.3,
        Off: -14.7,
        Net: 11.5,
        Rating: 1.8,
    },
    {
        Team: "PHO",
        Player: "Marcus.Morris",
        Min: "46%",
        Own: 13.8,
        Opp: 14.7,
        Net: -1,
        On: 6.9,
        Off: -0.4,
        Net: 7.3,
        Rating: 1.8,
    },
    {
        Team: "SAC",
        Player: "Cousins",
        Min: "61%",
        Own: 26.1,
        Opp: 18.2,
        Net: 8,
        On: -9,
        Off: 1.7,
        Net: -10.8,
        Rating: 1.7,
    },
    {
        Team: "CHI",
        Player: "Gibson",
        Min: "53%",
        Own: 15.8,
        Opp: 15.7,
        Net: 0.1,
        On: 7.4,
        Off: 2.4,
        Net: 5,
        Rating: 1.7,
    },
    {
        Team: "LAL",
        Player: "Young",
        Min: "50%",
        Own: 15.3,
        Opp: 11.3,
        Net: 4,
        On: -5.9,
        Off: -3,
        Net: -2.9,
        Rating: 1.7,
    },
    {
        Team: "LAL",
        Player: "Farmar",
        Min: "40%",
        Own: 10.6,
        Opp: 11.6,
        Net: -1,
        On: -0.4,
        Off: -7.1,
        Net: 6.7,
        Rating: 1.5,
    },
    {
        Team: "DAL",
        Player: "Dalembert",
        Min: "47%",
        Own: 16.7,
        Opp: 12.1,
        Net: 4.7,
        On: 0.4,
        Off: 5.3,
        Net: -4.9,
        Rating: 1.5,
    },
    {
        Team: "CHA",
        Player: "McRoberts",
        Min: "53%",
        Own: 15,
        Opp: 14.4,
        Net: 0.7,
        On: -3,
        Off: -6,
        Net: 3,
        Rating: 1.4,
    },
    {
        Team: "BKN",
        Player: "Blatche",
        Min: "44%",
        Own: 10.5,
        Opp: 13.9,
        Net: -3.4,
        On: 1.5,
        Off: -9.5,
        Net: 11,
        Rating: 1.4,
    },
    {
        Team: "DEN",
        Player: "Faried",
        Min: "52%",
        Own: 21.7,
        Opp: 18,
        Net: 3.7,
        On: -2.8,
        Off: 0.7,
        Net: -3.5,
        Rating: 1.3,
    },
    {
        Team: "CHA",
        Player: "Kidd-Gilchrist",
        Min: "60%",
        Own: 17.2,
        Opp: 19.2,
        Net: -2.1,
        On: -1.2,
        Off: -9.3,
        Net: 8.1,
        Rating: 1.3,
    },
    {
        Team: "IND",
        Player: "Watson",
        Min: "47%",
        Own: 9.7,
        Opp: 10.3,
        Net: -0.6,
        On: 11.6,
        Off: 7.4,
        Net: 4.2,
        Rating: 1,
    },
    {
        Team: "BKN",
        Player: "Livingston",
        Min: "46%",
        Own: 19.1,
        Opp: 21.5,
        Net: -2.4,
        On: -0.5,
        Off: -8.3,
        Net: 7.8,
        Rating: 1,
    },
    {
        Team: "NOH",
        Player: "Aminu",
        Min: "45%",
        Own: 13.8,
        Opp: 13.9,
        Net: 0,
        On: 3.3,
        Off: 0.7,
        Net: 2.6,
        Rating: 0.8,
    },
    {
        Team: "NYK",
        Player: "Shumpert",
        Min: "64%",
        Own: 13.4,
        Opp: 19.7,
        Net: -6.3,
        On: 0,
        Off: -14.8,
        Net: 14.8,
        Rating: 0.7,
    },
    {
        Team: "NYK",
        Player: "Bargnani",
        Min: "55%",
        Own: 21.4,
        Opp: 14.8,
        Net: 6.6,
        On: -10.5,
        Off: 1,
        Net: -11.5,
        Rating: 0.6,
    },
    {
        Team: "LAC",
        Player: "Crawford",
        Min: "54%",
        Own: 19.2,
        Opp: 10.6,
        Net: 8.6,
        On: -3.1,
        Off: 13.2,
        Net: -16.3,
        Rating: 0.3,
    },
    {
        Team: "LAL",
        Player: "Henry",
        Min: "42%",
        Own: 8.5,
        Opp: 10.8,
        Net: -2.4,
        On: -1.2,
        Off: -6.7,
        Net: 5.5,
        Rating: 0.3,
    },
    {
        Team: "DET",
        Player: "Stuckey",
        Min: "48%",
        Own: 17,
        Opp: 12.8,
        Net: 4.2,
        On: -7.5,
        Off: 0.4,
        Net: -7.9,
        Rating: 0.2,
    },
    {
        Team: "WAS",
        Player: "Gortat",
        Min: "68%",
        Own: 16.4,
        Opp: 19.1,
        Net: -2.7,
        On: -2.5,
        Off: -8.4,
        Net: 5.8,
        Rating: 0.2,
    },
    {
        Team: "SAS",
        Player: "Belinelli",
        Min: "43%",
        Own: 15.4,
        Opp: 15.4,
        Net: 0.1,
        On: 9.5,
        Off: 9.2,
        Net: 0.3,
        Rating: 0.2,
    },
    {
        Team: "WAS",
        Player: "Ariza",
        Min: "63%",
        Own: 15.6,
        Opp: 19.1,
        Net: -3.6,
        On: -1.7,
        Off: -9,
        Net: 7.2,
        Rating: 0,
    },
    {
        Team: "MIA",
        Player: "Wade",
        Min: "62%",
        Own: 19.4,
        Opp: 13.6,
        Net: 5.7,
        On: 3.2,
        Off: 14.7,
        Net: -11.5,
        Rating: 0,
    },
    {
        Team: "CLE",
        Player: "Miles",
        Min: "40%",
        Own: 18.8,
        Opp: 20.1,
        Net: -1.3,
        On: -5.3,
        Off: -7.8,
        Net: 2.5,
        Rating: 0,
    },
    {
        Team: "CHA",
        Player: "Henderson",
        Min: "67%",
        Own: 10.1,
        Opp: 10.7,
        Net: -0.6,
        On: -4.1,
        Off: -4.9,
        Net: 0.8,
        Rating: -0.2,
    },
    {
        Team: "PHO",
        Player: "Frye",
        Min: "51%",
        Own: 7.2,
        Opp: 12.8,
        Net: -5.6,
        On: 8.2,
        Off: -2.5,
        Net: 10.7,
        Rating: -0.2,
    },
    {
        Team: "NOH",
        Player: "Holiday",
        Min: "67%",
        Own: 14.6,
        Opp: 17.3,
        Net: -2.7,
        On: 3.4,
        Off: -1.2,
        Net: 4.6,
        Rating: -0.2,
    },
    {
        Team: "CHA",
        Player: "Walker",
        Min: "72%",
        Own: 13.7,
        Opp: 13.8,
        Net: -0.1,
        On: -4.6,
        Off: -4,
        Net: -0.6,
        Rating: -0.3,
    },
    {
        Team: "SAS",
        Player: "Duncan",
        Min: "47%",
        Own: 15.7,
        Opp: 13.3,
        Net: 2.5,
        On: 6.2,
        Off: 12.1,
        Net: -6,
        Rating: -0.3,
    },
    {
        Team: "ATL",
        Player: "Carroll",
        Min: "65%",
        Own: 12.1,
        Opp: 14.6,
        Net: -2.5,
        On: 5.7,
        Off: 2,
        Net: 3.7,
        Rating: -0.5,
    },
    {
        Team: "OKC",
        Player: "Westbrook",
        Min: "53%",
        Own: 18.1,
        Opp: 15.8,
        Net: 2.3,
        On: -0.8,
        Off: 5.3,
        Net: -6.2,
        Rating: -0.5,
    },
    {
        Team: "PHO",
        Player: "Green",
        Min: "52%",
        Own: 15.7,
        Opp: 15.9,
        Net: -0.3,
        On: 2.3,
        Off: 3.7,
        Net: -1.3,
        Rating: -0.6,
    },
    {
        Team: "IND",
        Player: "G.Hill",
        Min: "43%",
        Own: 12.7,
        Opp: 14.7,
        Net: -2,
        On: 10.6,
        Off: 8.5,
        Net: 2.2,
        Rating: -0.6,
    },
    {
        Team: "HOU",
        Player: "Howard",
        Min: "72%",
        Own: 20.4,
        Opp: 20.9,
        Net: -0.5,
        On: 2.2,
        Off: 3.2,
        Net: -1,
        Rating: -0.7,
    },
    {
        Team: "ORL",
        Player: "Nelson",
        Min: "64%",
        Own: 10.6,
        Opp: 14.1,
        Net: -3.5,
        On: 2,
        Off: -3,
        Net: 5,
        Rating: -0.7,
    },
    {
        Team: "NYK",
        Player: "WorldPeace",
        Min: "45%",
        Own: 13.8,
        Opp: 16,
        Net: -2.1,
        On: -4.2,
        Off: -6.2,
        Net: 2,
        Rating: -0.7,
    },
    {
        Team: "TOR",
        Player: "Gay",
        Min: "73%",
        Own: 16.6,
        Opp: 12.7,
        Net: 3.9,
        On: -2.9,
        Off: 7.2,
        Net: -10.1,
        Rating: -0.8,
    },
    {
        Team: "IND",
        Player: "Stephenson",
        Min: "70%",
        Own: 14.4,
        Opp: 11.2,
        Net: 3.2,
        On: 6.8,
        Off: 15.6,
        Net: -8.8,
        Rating: -0.8,
    },
    {
        Team: "MEM",
        Player: "Prince",
        Min: "52%",
        Own: 9.2,
        Opp: 14.3,
        Net: -5.1,
        On: 1.3,
        Off: -6.3,
        Net: 7.7,
        Rating: -0.8,
    },
    {
        Team: "DAL",
        Player: "Calderon",
        Min: "67%",
        Own: 15.2,
        Opp: 12.9,
        Net: 2.3,
        On: 0.6,
        Off: 7.8,
        Net: -7.2,
        Rating: -0.9,
    },
    {
        Team: "DET",
        Player: "Singler",
        Min: "46%",
        Own: 9,
        Opp: 15.7,
        Net: -6.7,
        On: 2.4,
        Off: -8.3,
        Net: 10.7,
        Rating: -0.9,
    },
    {
        Team: "BOS",
        Player: "Wallace",
        Min: "58%",
        Own: 10.5,
        Opp: 13.4,
        Net: -2.9,
        On: -2.3,
        Off: -5.2,
        Net: 2.9,
        Rating: -0.9,
    },
    {
        Team: "BOS",
        Player: "Faverani",
        Min: "40%",
        Own: 16.7,
        Opp: 17.7,
        Net: -1,
        On: -4,
        Off: -3.2,
        Net: -0.8,
        Rating: -0.9,
    },
    {
        Team: "MIL",
        Player: "Mayo",
        Min: "68%",
        Own: 16.1,
        Opp: 11.5,
        Net: 4.6,
        On: -12.4,
        Off: 0,
        Net: -12.4,
        Rating: -1,
    },
    {
        Team: "MIN",
        Player: "Pekovic",
        Min: "67%",
        Own: 17,
        Opp: 17.3,
        Net: -0.2,
        On: 7,
        Off: 10.6,
        Net: -3.6,
        Rating: -1.4,
    },
    {
        Team: "CLE",
        Player: "Varejao",
        Min: "65%",
        Own: 15.9,
        Opp: 19,
        Net: -3.1,
        On: -6.1,
        Off: -8.2,
        Net: 2.1,
        Rating: -1.4,
    },
    {
        Team: "OKC",
        Player: "Ibaka",
        Min: "68%",
        Own: 21.2,
        Opp: 17.5,
        Net: 3.7,
        On: -1.6,
        Off: 9.8,
        Net: -11.5,
        Rating: -1.4,
    },
    {
        Team: "UTA",
        Player: "Hayward",
        Min: "78%",
        Own: 18.2,
        Opp: 15.3,
        Net: 3,
        On: -13.8,
        Off: -3.7,
        Net: -10.1,
        Rating: -1.4,
    },
    {
        Team: "NYK",
        Player: "Felton",
        Min: "73%",
        Own: 11.2,
        Opp: 18.5,
        Net: -7.3,
        On: -2.7,
        Off: -12.3,
        Net: 9.5,
        Rating: -1.7,
    },
    {
        Team: "DET",
        Player: "Jennings",
        Min: "55%",
        Own: 19.6,
        Opp: 18.6,
        Net: 1,
        On: -6.8,
        Off: 0.7,
        Net: -7.5,
        Rating: -1.8,
    },
    {
        Team: "DET",
        Player: "Drummond",
        Min: "72%",
        Own: 23.3,
        Opp: 22.5,
        Net: 0.9,
        On: -5.5,
        Off: 2,
        Net: -7.5,
        Rating: -1.9,
    },
    {
        Team: "NOH",
        Player: "Smith",
        Min: "59%",
        Own: 16.1,
        Opp: 22.1,
        Net: -6,
        On: 4.4,
        Off: -1.7,
        Net: 6.1,
        Rating: -1.9,
    },
    {
        Team: "SAC",
        Player: "Thornton",
        Min: "59%",
        Own: 11.4,
        Opp: 13.4,
        Net: -2,
        On: -5.7,
        Off: -3.8,
        Net: -1.9,
        Rating: -2,
    },
    {
        Team: "PHI",
        Player: "Turner",
        Min: "74%",
        Own: 16.8,
        Opp: 17.6,
        Net: -0.8,
        On: -7.8,
        Off: -2.4,
        Net: -5.4,
        Rating: -2.3,
    },
    {
        Team: "BKN",
        Player: "Johnson",
        Min: "66%",
        Own: 11.7,
        Opp: 18.1,
        Net: -6.3,
        On: -3,
        Off: -8,
        Net: 5.1,
        Rating: -2.5,
    },
    {
        Team: "PHI",
        Player: "Anderson",
        Min: "68%",
        Own: 11,
        Opp: 18.1,
        Net: -7.1,
        On: -4.3,
        Off: -10.6,
        Net: 6.3,
        Rating: -2.7,
    },
    {
        Team: "DAL",
        Player: "Marion",
        Min: "66%",
        Own: 16.3,
        Opp: 15.9,
        Net: 0.4,
        On: 0,
        Off: 8.9,
        Net: -8.9,
        Rating: -2.7,
    },
    {
        Team: "ORL",
        Player: "Harkless",
        Min: "59%",
        Own: 11.3,
        Opp: 12.1,
        Net: -0.7,
        On: -2.5,
        Off: 4.2,
        Net: -6.6,
        Rating: -2.7,
    },
    {
        Team: "DEN",
        Player: "Foye",
        Min: "57%",
        Own: 8.4,
        Opp: 12.2,
        Net: -3.8,
        On: -1.4,
        Off: -0.8,
        Net: -0.6,
        Rating: -2.7,
    },
    {
        Team: "LAL",
        Player: "Johnson",
        Min: "48%",
        Own: 12.2,
        Opp: 16.9,
        Net: -4.8,
        On: -3.8,
        Off: -5,
        Net: 1.1,
        Rating: -2.8,
    },
    {
        Team: "DET",
        Player: "Smith",
        Min: "75%",
        Own: 16,
        Opp: 22.2,
        Net: -6.1,
        On: -2.5,
        Off: -6.1,
        Net: 3.6,
        Rating: -2.9,
    },
    {
        Team: "ORL",
        Player: "Oladipo",
        Min: "53%",
        Own: 8.3,
        Opp: 12.3,
        Net: -4,
        On: -0.2,
        Off: 0.6,
        Net: -0.8,
        Rating: -2.9,
    },
    {
        Team: "DEN",
        Player: "Hickson",
        Min: "49%",
        Own: 12.7,
        Opp: 18.4,
        Net: -5.7,
        On: -0.2,
        Off: -2,
        Net: 1.7,
        Rating: -3.2,
    },
    {
        Team: "MIA",
        Player: "Battier",
        Min: "47%",
        Own: 9.9,
        Opp: 16,
        Net: -6.1,
        On: 8.3,
        Off: 6.8,
        Net: 1.5,
        Rating: -3.5,
    },
    {
        Team: "PHO",
        Player: "Bledsoe",
        Min: "72%",
        Own: 24.9,
        Opp: 18.3,
        Net: 6.6,
        On: -3.8,
        Off: 20.1,
        Net: -24,
        Rating: -3.6,
    },
    {
        Team: "MIA",
        Player: "Bosh",
        Min: "54%",
        Own: 22.3,
        Opp: 20.5,
        Net: 1.8,
        On: 0.9,
        Off: 15.3,
        Net: -14.4,
        Rating: -3.6,
    },
    {
        Team: "HOU",
        Player: "Beverley",
        Min: "43%",
        Own: 12.1,
        Opp: 19.2,
        Net: -7.1,
        On: 4.2,
        Off: 1.2,
        Net: 2.9,
        Rating: -3.8,
    },
    {
        Team: "PHO",
        Player: "Plumlee",
        Min: "65%",
        Own: 15.8,
        Opp: 15.8,
        Net: 0,
        On: -1.2,
        Off: 10.6,
        Net: -11.8,
        Rating: -3.9,
    },
    {
        Team: "PHI",
        Player: "Young",
        Min: "66%",
        Own: 15.1,
        Opp: 17,
        Net: -1.9,
        On: -9.1,
        Off: -1,
        Net: -8.1,
        Rating: -3.9,
    },
    {
        Team: "DAL",
        Player: "Carter",
        Min: "43%",
        Own: 15,
        Opp: 19.7,
        Net: -4.7,
        On: 1.6,
        Off: 4.1,
        Net: -2.4,
        Rating: -4,
    },
    {
        Team: "PHO",
        Player: "Tucker",
        Min: "67%",
        Own: 12.5,
        Opp: 16.5,
        Net: -4,
        On: 1.6,
        Off: 5.6,
        Net: -3.9,
        Rating: -4,
    },
    {
        Team: "BOS",
        Player: "Bass",
        Min: "62%",
        Own: 14.7,
        Opp: 19.3,
        Net: -4.6,
        On: -4.7,
        Off: -1.7,
        Net: -3,
        Rating: -4.1,
    },
    {
        Team: "SAS",
        Player: "Leonard",
        Min: "58%",
        Own: 18.6,
        Opp: 17.9,
        Net: 0.7,
        On: 3.6,
        Off: 17.3,
        Net: -13.7,
        Rating: -4.1,
    },
    {
        Team: "BOS",
        Player: "Bradley",
        Min: "62%",
        Own: 12,
        Opp: 14,
        Net: -2,
        On: -6.7,
        Off: 1.7,
        Net: -8.4,
        Rating: -4.1,
    },
    {
        Team: "CHI",
        Player: "Hinrich",
        Min: "56%",
        Own: 11.6,
        Opp: 15,
        Net: -3.4,
        On: 2.4,
        Off: 8.3,
        Net: -5.9,
        Rating: -4.2,
    },
    {
        Team: "PHI",
        Player: "Wroten",
        Min: "52%",
        Own: 13.4,
        Opp: 16.2,
        Net: -2.8,
        On: -10,
        Off: -2.4,
        Net: -7.6,
        Rating: -4.4,
    },
    {
        Team: "ATL",
        Player: "Martin",
        Min: "44%",
        Own: 13.7,
        Opp: 19.2,
        Net: -5.6,
        On: 3.2,
        Off: 5.4,
        Net: -2.2,
        Rating: -4.5,
    },
    {
        Team: "POR",
        Player: "Williams",
        Min: "55%",
        Own: 12.6,
        Opp: 17.8,
        Net: -5.2,
        On: 3,
        Off: 7.1,
        Net: -4.1,
        Rating: -4.8,
    },
    {
        Team: "HOU",
        Player: "Parsons",
        Min: "78%",
        Own: 16.5,
        Opp: 16.3,
        Net: 0.3,
        On: -0.9,
        Off: 14.5,
        Net: -15.4,
        Rating: -4.9,
    },
    {
        Team: "TOR",
        Player: "Valanciunas",
        Min: "55%",
        Own: 14.4,
        Opp: 20.4,
        Net: -5.9,
        On: -1.6,
        Off: 1.6,
        Net: -3.2,
        Rating: -5,
    },
    {
        Team: "UTA",
        Player: "Favors",
        Min: "71%",
        Own: 18.6,
        Opp: 18.9,
        Net: -0.3,
        On: -15.8,
        Off: -1.2,
        Net: -14.5,
        Rating: -5.1,
    },
    {
        Team: "SAC",
        Player: "Vasquez",
        Min: "57%",
        Own: 15.3,
        Opp: 19.8,
        Net: -4.5,
        On: -7.6,
        Off: -1.3,
        Net: -6.3,
        Rating: -5.1,
    },
    {
        Team: "ORL",
        Player: "Moore",
        Min: "47%",
        Own: 9.7,
        Opp: 17.9,
        Net: -8.2,
        On: 0.6,
        Off: -0.2,
        Net: 0.8,
        Rating: -5.2,
    },
    {
        Team: "MIL",
        Player: "Neal",
        Min: "47%",
        Own: 12.4,
        Opp: 11.4,
        Net: 1,
        On: -17.8,
        Off: -0.2,
        Net: -17.6,
        Rating: -5.2,
    },
    {
        Team: "MIL",
        Player: "Butler",
        Min: "51%",
        Own: 10,
        Opp: 15.7,
        Net: -5.7,
        On: -10.7,
        Off: -6.1,
        Net: -4.6,
        Rating: -5.3,
    },
    {
        Team: "MIN",
        Player: "Cunningham",
        Min: "41%",
        Own: 13,
        Opp: 15,
        Net: -2,
        On: 0.4,
        Off: 13.6,
        Net: -13.1,
        Rating: -5.7,
    },
    {
        Team: "SAC",
        Player: "McLemore",
        Min: "43%",
        Own: 10.7,
        Opp: 20.2,
        Net: -9.5,
        On: -4.4,
        Off: -5.2,
        Net: 0.8,
        Rating: -6.1,
    },
    {
        Team: "LAL",
        Player: "Blake",
        Min: "66%",
        Own: 15,
        Opp: 18.3,
        Net: -3.2,
        On: -8.7,
        Off: 4,
        Net: -12.6,
        Rating: -6.4,
    },
    {
        Team: "SAC",
        Player: "Salmons",
        Min: "55%",
        Own: 8,
        Opp: 12.8,
        Net: -4.8,
        On: -9.3,
        Off: 0.5,
        Net: -9.8,
        Rating: -6.5,
    },
    {
        Team: "CLE",
        Player: "Jack",
        Min: "53%",
        Own: 11.2,
        Opp: 15.9,
        Net: -4.7,
        On: -11.8,
        Off: -1.1,
        Net: -10.7,
        Rating: -6.7,
    },
    {
        Team: "LAL",
        Player: "Gasol",
        Min: "61%",
        Own: 15,
        Opp: 17.3,
        Net: -2.3,
        On: -10.5,
        Off: 5.1,
        Net: -15.7,
        Rating: -6.8,
    },
    {
        Team: "LAC",
        Player: "Dudley",
        Min: "57%",
        Own: 5.5,
        Opp: 15.3,
        Net: -9.8,
        On: 3.2,
        Off: 5.8,
        Net: -2.6,
        Rating: -7.4,
    },
    {
        Team: "MIA",
        Player: "Chalmers",
        Min: "51%",
        Own: 17.9,
        Opp: 19.5,
        Net: -1.6,
        On: -1.9,
        Off: 17.5,
        Net: -19.4,
        Rating: -7.5,
    },
    {
        Team: "POR",
        Player: "Lopez",
        Min: "62%",
        Own: 13.4,
        Opp: 25.7,
        Net: -12.2,
        On: 5.5,
        Off: 3.9,
        Net: 1.6,
        Rating: -7.6,
    },
    {
        Team: "NOH",
        Player: "Evans",
        Min: "50%",
        Own: 10.6,
        Opp: 18.2,
        Net: -7.6,
        On: -2.2,
        Off: 6,
        Net: -8.2,
        Rating: -7.8,
    },
    {
        Team: "CHA",
        Player: "Taylor",
        Min: "52%",
        Own: 7.7,
        Opp: 13.3,
        Net: -5.5,
        On: -10.3,
        Off: 2.1,
        Net: -12.4,
        Rating: -7.8,
    },
    {
        Team: "UTA",
        Player: "Lucas",
        Min: "52%",
        Own: 5.2,
        Opp: 14.2,
        Net: -9.1,
        On: -14.1,
        Off: -8.7,
        Net: -5.4,
        Rating: -7.8,
    },
    {
        Team: "CHI",
        Player: "Noah",
        Min: "61%",
        Own: 18.4,
        Opp: 22.4,
        Net: -4,
        On: -1.2,
        Off: 14.6,
        Net: -15.8,
        Rating: -8,
    },
    {
        Team: "MEM",
        Player: "Miller",
        Min: "49%",
        Own: 10.8,
        Opp: 19.5,
        Net: -8.6,
        On: -6,
        Off: 1.2,
        Net: -7.2,
        Rating: -8.2,
    },
    {
        Team: "UTA",
        Player: "Kanter",
        Min: "70%",
        Own: 16.8,
        Opp: 24,
        Net: -7.2,
        On: -14.7,
        Off: -4.2,
        Net: -10.4,
        Rating: -8.3,
    },
    {
        Team: "OKC",
        Player: "Sefolosha",
        Min: "54%",
        Own: 10.5,
        Opp: 16.7,
        Net: -6.2,
        On: -4.5,
        Off: 9.7,
        Net: -14.2,
        Rating: -8.9,
    },
    {
        Team: "CLE",
        Player: "Gee",
        Min: "42%",
        Own: 8.9,
        Opp: 12.9,
        Net: -3.9,
        On: -18.3,
        Off: 1.4,
        Net: -19.6,
        Rating: -9.2,
    },
    {
        Team: "SAC",
        Player: "Patterson",
        Min: "43%",
        Own: 7.8,
        Opp: 22.1,
        Net: -14.3,
        On: -5,
        Off: -4.8,
        Net: -0.1,
        Rating: -9.6,
    },
    {
        Team: "SAC",
        Player: "Thompson",
        Min: "42%",
        Own: 7.4,
        Opp: 19.6,
        Net: -12.3,
        On: -7.5,
        Off: -3,
        Net: -4.4,
        Rating: -9.7,
    },
    {
        Team: "ORL",
        Player: "Maxiell",
        Min: "44%",
        Own: 8.2,
        Opp: 15.4,
        Net: -7.2,
        On: -9.1,
        Off: 7.4,
        Net: -16.5,
        Rating: -10.3,
    },
    {
        Team: "WAS",
        Player: "Webster",
        Min: "55%",
        Own: 16.6,
        Opp: 18,
        Net: -1.4,
        On: -17.1,
        Off: 11.3,
        Net: -28.4,
        Rating: -10.4,
    },
    {
        Team: "UTA",
        Player: "Jefferson",
        Min: "59%",
        Own: 9.5,
        Opp: 19.3,
        Net: -9.8,
        On: -16.8,
        Off: -4,
        Net: -12.9,
        Rating: -10.8,
    },
    {
        Team: "CHI",
        Player: "Rose",
        Min: "57%",
        Own: 8.5,
        Opp: 16.4,
        Net: -8,
        On: -2.2,
        Off: 14.6,
        Net: -16.8,
        Rating: -10.9,
    },
    {
        Team: "BKN",
        Player: "Garnett",
        Min: "41%",
        Own: 7.3,
        Opp: 18.5,
        Net: -11.2,
        On: -12.2,
        Off: 0.6,
        Net: -12.7,
        Rating: -11.7,
    },
    {
        Team: "CHA",
        Player: "Biyombo",
        Min: "52%",
        Own: 11.2,
        Opp: 21.8,
        Net: -10.6,
        On: -11.2,
        Off: 2.9,
        Net: -14.1,
        Rating: -11.8,
    },
    {
        Team: "BOS",
        Player: "Olynyk",
        Min: "46%",
        Own: 9.1,
        Opp: 26.5,
        Net: -17.4,
        On: -10.6,
        Off: 2.5,
        Net: -13.1,
        Rating: -16,
    },
];